services:
  shortmyurl-app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://seu-endereco-de-ip:27017/shortmyurl    
    networks:
      - mongo-network

networks:
  mongo-network:
    external: true